# Configuracoes de ambiente de desenvolvimento
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/lumineedu_binario
spring.datasource.username=lumineedu
spring.datasource.password=lumineedu

app.storage.diretorio=./armazenamento-dev
app.storage.subdiretorio=arquivos
app.storage.max-tamanho-bytes=10485760
app.storage.max-tamanho-hd-bytes=2147483648

app.security.tokens-validos=token-secreto-lumine,admin-token,lumine-key

server.port=8080

logging.level.com.lumineedu.binario=DEBUG
