-- Dados iniciais de exemplo (metadados dos arquivos).
-- O conteudo binario nao e armazenado no banco de dados; ele esta no disco local.

INSERT INTO tb_arquivo (
    nome_original,
    nome_arquivo,
    caminho_relativo,
    caminho_fisico,
    tamanho_bytes,
    tipo_mime,
    descricao,
    data_criacao,
    data_atualizacao,
    ativo,
    data_desativacao,
    hash
) VALUES
    ('foto_exemplo.jpg',
     'foto_exemplo.jpg',
     'arquivos/foto_exemplo.jpg',
     '/home/lumineedu/armazenamento/arquivos/foto_exemplo.jpg',
     524288,
     'image/jpeg',
     'Exemplo de arquivo de imagem',
     NOW(),
     NOW(),
     true,
     NULL,
     '74d197a3c20b3d1d2c8e1b8c0f0c5b3a9d6e2f4a8b1c3d5e7f9a0b2c4d6e8f1a'),
    ('documento.png',
     'documento.png',
     'arquivos/documento.png',
     '/home/lumineedu/armazenamento/arquivos/documento.png',
     1048576,
     'image/png',
     'Exemplo de arquivo PNG',
     NOW(),
     NOW(),
     true,
     NULL,
     'a1b2c3d4e5f60718293a4b5c6d7e8f9011223344556677889900aabbccddeeff');
